### ISSUE TITLE
Where to link to my badge-code - it's placed in separate GH repo?

### ISSUE THREAD

**Issue by rand00** [bornhack/badge2020#8]
Just uploaded my badge-code to:
https://github.com/rand00/bornhack2020-badge_generative-animations
.. and I heard that you were interested in linking to peoples code from this repo? 

Thanks for a nice festival (:

**Comment by flummer** [comment]
Thank you for sharing, I'll definitely take a look at it.

The easiest is probably a link in the readme file, maybe a section in the bottom with links to projects, I think that would be cool.
